### ISSUE TITLE
immunization Fhir IG vs PH-Core Dependency issue

### ISSUE THREAD

**Issue by niccoreyes** [niccoreyes/aiscream-jpa#2]
Notable issues with the ph-core dependency created by:
```
2025-06-14T13:39:20.153Z  INFO 1 --- [           main] o.h.f.u.npm.BasePackageCacheManager      : Failed to resolve package example.fhir.ph.core#current from server: [https://packages2.fhir.org/packages⁠](https://packages2.fhir.org/packages%E2%81%A0) (Not found)
```

Notice how 
_**example.fhir.ph.core#current**_ is attempted to be called from server **_https://packages2.fhir.org/packages⁠_**

This should be called from **_https://build.fhir.org/ig_** instead

Since the immunizationfhirig is configured to be dependent to the core via fsh, this might not be recognized with the #current version and it calls from the main published fhir repository. There has to be a way to route dependencies to the build.fhir dev repoitory

![Image](https://github.com/user-attachments/assets/298e56d4-e9c9-495e-9e45-c19fa5655801)

**Comment by jgsuess** [comment]
I had to think about this overnight and I believe there are some hacks that we could do to work around the underlying issue for the time being:

* load the dependency that is required directly before the one that references it this means that it's already in the cash when the resolution occurs.
* use an external tool like [UploadIFG](https://github.com/brianpos/UploadFIG). I am using when I work with IG builds.

**Comment by jgsuess** [comment]
Do you have a tag where the testcase is checked in, so I can reproduce? I have a feeling that the descriptor for the Immunization IG may be wrong.

**Comment by jgsuess** [comment]
I think I have got it:

Immunization IG specifies like [this](https://github.com/UP-Manila-SILab/immunizationfhirig/blob/3538c3bf993e322202a00e1ca37cbee398498bf8/sushi-config.yaml#L27C1-L28C32):

```yaml
dependencies:
  example.fhir.ph.core: current
```

I think `current` only works for IG builder, so the package is missing the URL for the download, and should look like this:

```yaml
dependencies:
  example.fhir.ph.core: current
  uri: http://build.fhir.org/ig/UP-Manila-SILab/ph-core/package.r4.tgz
```

or this:

```yaml
dependencies:
  example.fhir.ph.core: "http://build.fhir.org/ig/UP-Manila-SILab/ph-core/package.r4.tgz"
``

As per [spec](https://fshschool.org/docs/sushi/configuration/#dependencies)

```yaml
dependencies:
  hl7.fhir.us.core:
    id: uscore
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    version: 3.1.0
```

That should lead to the correct fully qualified package URL being embedded.

Unfortunately, I am not a committer on Immunization IG.
